#define IDENTIFIER 1
#define CONSTANT 100
#define MAGIE 2
#define NEATA 3
#define NB 4
#define PROGRAM 5
#define IF 6
#define ELSE 7
#define WHILE 8
#define FOR 9
#define IN 10
#define OUT 11
#define STRING 12
#define CHAR 13
#define INT 14
#define BOOL 15
#define STRUCT 16
#define NUMAR 17
#define FALSE 18
#define TRUE 19